version: 2.1
orbs:
    terraform: devops-workflow/terraform@0.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: pip install pandas boto3 botocore requests s3fs
      - run: 
          name: Run Unit Tests
          command: |
            cd powerflex/
            python -m unittest
          
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run: |
          cd powerflex
          terraform init
          terraform plan

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
