version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: echo 'Hello, I need to install the build deps when they get specified'
      - run: 
          name: Run Unit Tests
          command: echo 'Run unit tests when I have them'
          
  deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - run: |
          echo 'run terraform to deploy this out when ready'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
