version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: pip install pandas boto3 botocore requests s3fs
      - run: 
          name: Run Unit Tests
          command: |
            cd powerflex/
            python -m unittest
          
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - run: |
          echo 'run terraform to deploy this out when ready'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
