version: 2.1

jobs:
  build:
    docker:
      - image: claranet/terraform-python

    steps:
      - checkout
      - run:
          name: Python version
          command: |
            python --version
            python3 --version
      - run:
          name: Install build dependencies
          command: pip install pandas boto3 botocore requests s3fs
      - run: 
          name: Run Unit Tests
          command: |
            cd powerflex/
            python -m unittest
          
  deploy:
    docker:
      - image: claranet/terraform-python

    steps:
      - checkout
      - run: |
          terraform --version

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
